### ISSUE TITLE
Helix missing LibC initially

### ISSUE THREAD

**Issue by AppearedOne** [blinksh/build-hacker-tools#15]
Helix is missing GLIBC_2.32-2.34, which is supposed to be at /lib/x86_64-linux-gnu/libc.so. However all I could find in that directory is libc version 2.31

**Comment by yury** [comment]
Hello @AppearedOne 

Yep, we [fixed that already](https://github.com/blinksh/build-hacker-tools/commit/7c97e6665f4e69fad89432cf494c9771ee7002a8) but didn't pushed to production yet.

**Comment by yury** [comment]
Hello @AppearedOne 

We pushed image with fix to production. Please try again.

**Comment by AppearedOne** [comment]
Yes, @yury 
Ive tried again and helix now seems to be working without any issues,
thanks

**Comment by yury** [comment]
Ok, closing this issue feel free to reopen if needed.
